### PR TITLE
added component button-group

### PR DESCRIPTION
**Pull request by nguasch**
new component button group.

Please,review: @larnedo @PablitoGS @nucliweb

### CODE REVIEW

**Comment by nguasch** [comment]
finaly, I added button-group to button component. 
Please, review: @larnedo @PablitoGS  @nucliweb

**Comment by PablitoGS** [comment]
@nguasch button don´t find dist directory in typography

**Comment by PablitoGS** [comment]
:+1:

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
