### PR TITLE
added new component notifications

### PR DESCRIPTION
**Pull request by PablitoGS**
Please review @nguasch @nucliweb @larnedo

### CODE REVIEW

**Comment by nguasch** [comment]
:+1:

**Comment by nucliweb** [comment]
@PablitoGS please add dependency in `package.json` and include in `/src/index.scss` for add the component in to **SUI Framework**

Thanks

**Comment by PablitoGS** [comment]
@nucliweb I added dependencie and import , but I think we could add to SUI when they the component is validated and published in npm.

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
