### PR TITLE
Feature/dist

### PR DESCRIPTION
**Pull request by larnedo**
Removed dist folder and added on .gitignore file.

@nucliweb @PablitoGS Please review code.

### CODE REVIEW

**Comment by nucliweb** [comment]
@larnedo I don't see the `.gitignore` file

**Comment by PablitoGS** [comment]
@larnedo @nucliweb gitignore file it´s ok in master to dont´t up dist. Do you say remove line referred to docs?

# SUI files ignore

docs

**Comment by nucliweb** [comment]
:+1:

**Comment by PablitoGS** [comment]
:+1:

**Pull request merged**
