### PR TITLE
Feature/sui framework ignorefiles

### PR DESCRIPTION
**Pull request by PablitoGS**
Added npmignore, please review to publish in npm @nguasch @nucliweb

### CODE REVIEW

**Comment by nguasch** [comment]
Can you add too the /dist folder in .gitignore to avoid adding this directory on GitHub? @PablitoGS

**Comment by PablitoGS** [comment]
@nguasch done

**Comment by nguasch** [comment]
Thanks @PablitoGS 

:+1:

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
