### PR TITLE
added vars to form component

### PR DESCRIPTION
**Pull request by PablitoGS**
I added new vars to form component, review please @nguasch @larnedo @nucliweb

### CODE REVIEW

**Comment by nguasch** [comment]
`_settings.scss` needs `@import 'components/form';`
review too `_form.scss`, because there are two syntax error on lines 7 and 8.
please, fix it @PablitoGS

**Comment by PablitoGS** [comment]
@nguasch  done!

**Comment by larnedo** [comment]
:+1:

**Comment by nguasch** [comment]
:+1:

**Pull request merged**
