### PR TITLE
new package main to main styles of components and base elements

### PR DESCRIPTION
**Pull request by PablitoGS**
Please review @nguasch @larnedo @nucliweb

### CODE REVIEW

**Comment by larnedo** [comment]
@PablitoGS Could you fix version to v0.1.0? I think also you should use fonts' mixin to define body's font-size and line-height.
`npm run lint` is generating errors, could you check it?

**Comment by PablitoGS** [comment]
@larnedo  done!

**Comment by nguasch** [comment]
:+1:

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
