### PR TITLE
Component Stickers

### PR DESCRIPTION
**Pull request by larnedo**
@nucliweb @PablitoGS @nguasch Please review code.

### CODE REVIEW

**Comment by nucliweb** [comment]
**Code reviewing**

**Comment by nucliweb** [comment]
This is a new component, please add dependency in `package.json` and import in `index.scss` in **SUI**

Thanks

**Comment by larnedo** [comment]
@nucliweb I think I'm right, I have followed the steps that you recommend us:

```
Passes:

- ​*PR*​ del nou component
- Merge (Si tot està ok)
- Publicar a ​*npm*​ el componente
- ​*PR*​ a SUI amb les dependències del nou component
- Merge (Si tot està ok)
- Publicar a ​*npm*​ la nova versión de ​*SUI*​
- `git release` de ​*SUI*​(edited)

```

Has change the steps?

**Comment by PablitoGS** [comment]
**Code reviewing**

**Comment by PablitoGS** [comment]
@larnedo please publish on surge this component.
npm run docs from sticker package

**Comment by larnedo** [comment]
@PablitoGS Done it!

**Comment by PablitoGS** [comment]
:+1:

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
