### PR TITLE
Updated gitignore

### PR DESCRIPTION
**Pull request by larnedo**
@nguasch @PablitoGS @nucliweb Please review code.

### CODE REVIEW

**Comment by nucliweb** [comment]
Yes, it's the same.
After some research, very few projects use `/` as the first character of the expression.
So we'll use `**/dist`

**Comment by nguasch** [comment]
Ok, 
:+1:

**Comment by nucliweb** [comment]
:+1:

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
