### PR TITLE
Refactor input and textarea

### PR DESCRIPTION
**Pull request by PablitoGS**
I´ve ordered the structure of this css for input and textarea. Added placeholder and changed some vars
Please review @nguasch @nucliweb

### CODE REVIEW

**Comment by nucliweb** [comment]
:+1:

**Comment by nguasch** [comment]
there are two lint errors:

```
src/_form.scss:169 [W] Indentation: Line should be indented 2 spaces, but was indented 4 spaces
src/_form.scss:173 [W] Indentation: Line should be indented 2 spaces, but was indented 4 spaces
```

please, review @PablitoGS

**Comment by PablitoGS** [comment]
done @nguasch

**Comment by nguasch** [comment]
:+1:

**Comment by PablitoGS** [comment]
@nguasch added success state

**Comment by nguasch** [comment]
:+1:

**Pull request merged**
