### PR TITLE
Feature/reset box sizing

### PR DESCRIPTION
**Pull request by PablitoGS**
I fixed box-sizing in reset to border-box. Please review @nguasch @larnedo @nucliweb

### CODE REVIEW

**Comment by nucliweb** [comment]
I prefer to leave the `box-sizing: inherit` and add `box-sizing: border-box` in **html** tag. And selector `*`

Ref. https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

**Comment by PablitoGS** [comment]
@nucliweb done, thanks

**Comment by nguasch** [comment]
:+1:

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
