### PR TITLE
Added package sui-base to SUI Framework

### PR DESCRIPTION
**Pull request by nucliweb**
- Added package _sui-base_ to SUI Framework

Please review @larnedo @nguasch @PablitoGS

### CODE REVIEW

**Comment by PablitoGS** [comment]
@nucliweb  Maybe it's better this order for the imports:

 @import '~sui-settings/src/settings';
 @import '~sui-typography/src/typography';
 @import '~sui-base/src/base';

typography brings the @font-face

**Comment by nucliweb** [comment]
Done!

**Comment by PablitoGS** [comment]
cool :) :+1:

**Comment by larnedo** [comment]
:+1:

**Pull request merged**
