### PR TITLE
added reset dependencies

### PR DESCRIPTION
**Pull request by nguasch**
Please review @larnedo @nucliweb

### CODE REVIEW

**Comment by PablitoGS** [comment]
:+1:

**Comment by larnedo** [comment]
@nguasch It's seems that there is some problem with typography because it's not working properly.

**Comment by nguasch** [comment]
@larnedo yes. I'm checking it

**Comment by PablitoGS** [comment]
:+1:

**Comment by larnedo** [comment]
:+1:

**Pull request merged**
